<a href="https://colab.research.google.com/github/shubhamkoul007/Acquire-Valued-Shopper-Challenge-Team1-TDL/blob/main/Python_for_Data_Science.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Chapter 1- Python Basics**

**Data Types**

**Numbers**

In [ ]:
a=3
b=2

#Addition
print(a+b)

#Subtraction
print(a-b)

#Multiplication
print(a*b)

#Division
print(a/b)

#a raised to the power b
print(a**b)

#Remainder using a modulus b
print(a%b)

5
1
6
1.5
9
1


**Lists**

In [ ]:
l=['a','b','c']

In [ ]:
l

['a', 'b', 'c']

In [ ]:
l.append('d')

In [ ]:
l

['a', 'b', 'c', 'd']

In [ ]:
l[0]

'a'

In [ ]:
l[1:]

['b', 'c', 'd']

In [ ]:
l[:3]

['a', 'b', 'c']

In [ ]:
l[1:2]

['b']

In [ ]:
l.pop()

'c'

In [ ]:
l

['a', 'b']

In [ ]:
'x' in l

False

In [ ]:
'x' in ['x','y','z']

True

In [ ]:
nst=[1,2,3,[4,5,[6]]]
nst[3]

[4, 5, [6]]

In [ ]:
nst[3][1]

5

In [ ]:
nst[3][2][0]

**Dictionaries**

In [ ]:
d = {'key1':'item1','key2':'item2'}

In [ ]:
d

{'key1': 'item1', 'key2': 'item2'}

In [ ]:
d['key1']

'item1'

In [ ]:
d.keys()

dict_keys(['key1', 'key2'])

In [ ]:
d.items()

dict_items([('key1', 'item1'), ('key2', 'item2')])

**Strings**

In [ ]:
s1="TATA"

In [ ]:
s2="DIGITAL"

In [ ]:
s3=s1+" " +s2
print(s3)

'TATA DIGITAL'

In [ ]:
s3.lower()

In [ ]:
s3.upper()

In [ ]:
s3.split()

In [ ]:
s4="Alas! I can't learn python quickly."

In [ ]:
s4.split('!')

['Alas', " I can't learn python quickly."]

In [ ]:
s4.split('!')[1]

" I can't learn python quickly."

**Sets**

In [ ]:
s={1,2,3,4,5}

In [ ]:
s={1,2,2,3,3,3,4,4,4,4,5,5,5,5,5}

**if, elif and else**

In [ ]:
if 1 < 2:
    print('yep!')

In [ ]:
if 1 < 2:
    print('first')
else:
    print('last')

In [ ]:
if 1 == 2:
    print('first')
elif 3 == 3:
    print('middle')
else:
    print('Last')

**For and While loop**

In [ ]:
range(5)

In [ ]:
for i in range(5):
    print(i)

In [ ]:
list(range(5))

In [ ]:
r = [1,2,3,4,5]

In [ ]:
for i in r:
    print(i)

In [ ]:
i = 1
while i < 5:
    print('i is: {}'.format(i))
    i = i+1

i is: 1
i is: 2
i is: 3
i is: 4


In [ ]:
x = [1,2,3,4]

In [ ]:
out = []
for item in x:
    out.append(item**2)
print(out)

In [ ]:
[item**2 for item in x]

**Functions**

In [ ]:
def my_func(param1='default'):
    """
    Docstring goes here.
    """
    print(param1)

In [ ]:
my_func()

In [ ]:
my_func('new param')

In [ ]:
my_func(param1='new param')

In [ ]:
def square(x):
    return x**2

In [ ]:
out = square(2)
print(out)

**Lambda Expressions**

In [ ]:
sqr = lambda a : a**2
print(sqr(2))

In [ ]:
seq = [1,2,3,4,5]

**Map and Filter**

In [ ]:
map(times2,seq)

In [ ]:
list(map(square,seq))

In [ ]:
list(map(sqr,seq))

In [ ]:
filter(lambda item: item%2 == 0,seq)

In [ ]:
list(filter(lambda item: item%2 == 0,seq))

**Chapter 2 -Introduction to Numpy(python data science handbook)**


No matter what the data,first step in making them analyzable will be to transform them into arrays of numbers.

Efficient storage and manipulation of numerical arrays is absolutely fundamental to the process of doing data science.

Specialized tool that python has for handling such numerical arrays-NumPy package and Pandas package.

NumPy (short for Numerical Python) provides
an efficient interface to store and operate on dense data buffers.
NumPy arrays provide much
more efficient storage and data operations as the arrays grow larger in size than lists.



In [ ]:
import numpy as np

In [ ]:
np.__version__

'1.18.5'

In [ ]:
np?

**Understanding Data Types in Python**

Effective data-driven science and computation requires understanding how data is
stored and manipulated. This section outlines and contrasts how arrays of data are
handled in the Python language itself, and how NumPy improves on this.

Data types are dynamically inferred.

**A Python Integer Is More Than Just an Integer**


when we define an integer in Python, such as
x = 10000, x is not just a “raw” integer. It’s actually a pointer to a compound C structure,
which contains several values.

A single integer in Python 3.4 actually contains four pieces:
• ob_refcnt, a reference count that helps Python silently handle memory allocation
and deallocation
• ob_type, which encodes the type of the variable
• ob_size, which specifies the size of the following data members
• ob_digit, which contains

A Python integer is a pointer to a position in
memory containing all the Python object information, including the bytes that contain
the integer value.

**A Python List Is More Than Just a List**



In [ ]:
L3=[True,"creation",3.0,4]

But this flexibility comes at a cost: to allow these flexible types, each item in the list
must contain its own type info, reference count, and other information—that is, each
item is a complete Python object.

At the implementation level, the array essentially contains a single pointer to one contiguous
block of data. The Python list, on the other hand, contains a pointer to a
block of pointers, each of which in turn points to a full Python object like the Python integer.

The advantage of the list is flexibility: because each list
element is a full structure containing both data and type information, the list can be
filled with data of any desired type. Fixed-type NumPy-style arrays lack this flexibility,
but are much more efficient for storing and manipulating data.

**Fixed-Type Arrays in Python**

In [ ]:
import array
L=list(range(10))
A=array.array('i',L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

While Python’s array object provides efficient storage of array-based data, NumPy adds to this efficient operations on that data

**Creating Arrays from Python Lists**

In [ ]:
A=np.array([1,2,3,4],dtype='float32')

In [ ]:
#multidimensional arrays
np.array([range(i,i+3) for i in range(3)])

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [ ]:
for i in range(3):
  print(range(i,i+3))

range(0, 3)
range(1, 4)
range(2, 5)


**Creating Arrays from Scratch**

In [ ]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [ ]:
np.ones((3,3),dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.full((2,3),3.14)

array([[3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14]])

In [ ]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [ ]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
np.random.random((3,3))

array([[0.89020099, 0.99304152, 0.02411159],
       [0.12250582, 0.43999855, 0.64062683],
       [0.75065739, 0.78916632, 0.57904854]])

In [ ]:
np.random.normal(0,1,(3,3))
#0 mean and 1 std deviation

array([[ 1.07205549,  0.33376062,  0.70419279],
       [-1.01544406,  0.42350841,  0.91215136],
       [-0.59726534, -1.72404557,  0.86541784]])

In [ ]:
np.random.randint(0,10,(3,3))

array([[8, 4, 2],
       [3, 4, 9],
       [4, 4, 6]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**NumPy Standard Data Types**

NumPy arrays contain values of a single type.

bool_,int_,intc ,intp ,int8,int16,int32,int64,uint8,uint16,uint32,uint64,float_,float16,float32,float64,complex_,complex64,complex128.

In [ ]:
np.zeros(5,dtype='int16')

array([0, 0, 0, 0, 0], dtype=int16)

In [ ]:
np.zeros(4,dtype=np.int16)

array([0, 0, 0, 0], dtype=int16)

**NumPy Array Attributes**

Determining the size, shape, memory consumption, and data types of arrays

In [ ]:
x1=np.random.randint(10,size=(3,4))
x1

array([[5, 8, 4, 8],
       [0, 5, 1, 5],
       [1, 7, 6, 9]])

In [ ]:
print("dim = \t",x1.ndim,"\t shape is ",x1.shape,"\t size is ",x1.size)

dim = 	 2 	 shape is  (3, 4) 	 size is  12


In [ ]:
x1.dtype

dtype('int64')

In [ ]:
x1.itemsize,x1.nbytes

(8, 96)

**Array Indexing: Accessing Single Elements**

In [ ]:
x1[-1]

array([1, 7, 6, 9])

In [ ]:
x1[0,1]

8

In [ ]:
x1[0,1]=89
x1

array([[ 5, 89,  4,  8],
       [ 0,  5,  1,  5],
       [ 1,  7,  6,  9]])

**Array Slicing: Accessing Subarrays**

To access subarrays with slice notation,marked by colon(:) character.


x[start:stop:step].

If any of these are unspecified, they default to the values start=0, stop=size of
dimension, step=1.

In [ ]:
x=np.array(range(10))
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x[::2]

array([0, 2, 4, 6, 8])

In [ ]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [ ]:
x[5::-2]

array([5, 3, 1])

In [ ]:
x1

array([[ 5, 89,  4,  8],
       [ 0,  5,  1,  5],
       [ 1,  7,  6,  9]])

In [ ]:
x1[:2,1:3]

array([[89,  4],
       [ 5,  1]])

In [ ]:
x1[::-1,::-1]

array([[ 9,  6,  7,  1],
       [ 5,  1,  5,  0],
       [ 8,  4, 89,  5]])

**Subarrays as no-copy views**

Array slices is that they
return views rather than copies of the array data.

If we modify the subarray, we’ll see that the original array is changed!

In [ ]:
#creating copies of arrays
x1_subarry_copy=x1[:2,1:3].copy()
print(x1_subarry_copy)

[[89  4]
 [ 5  1]]


In [ ]:
x1_subarry_copy[0,0]=99
x1_subarry_copy

array([[99,  4],
       [ 5,  1]])

In [ ]:
x1
#x1 is not modified

array([[ 5, 89,  4,  8],
       [ 0,  5,  1,  5],
       [ 1,  7,  6,  9]])

**Reshaping of Arrays**

In [ ]:
a1=np.array(range(9)).reshape((3,3))
a1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
a2=np.array([1,2,3])
a2.shape

(3,)

In [ ]:
a2=a2.reshape((3,1))
print(a2.shape)
print(a2)

(3, 1)
[[1]
 [2]
 [3]]


In [ ]:
#row vector via new axis
a3=np.array([1,2,3,4,5])
print(a3.shape)
a3=a3[np.newaxis,:]
a3

(5,)


array([[1, 2, 3, 4, 5]])

In [ ]:
a3.shape

(1, 5)

In [ ]:
#col vector via newaxis
a5=np.array([1,4,5,6,8])
print(a5.shape)
#a4=a4.reshape((5,1))

a5=a5[:,np.newaxis]
print(a5)

(5,)
[[1]
 [4]
 [5]
 [6]
 [8]]


**Array Concatenation and Splitting**



In [ ]:
#concatenation 
#np.concatenate,np.vstack and np.hstack
x=np.array([1,2,3,4])
y=np.array([5,6,7,8])
#takes tuple or list of arrays as first argument
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
z=np.array([[1,2,3],[4,5,6]])
np.concatenate([z,z])#concatenate along first axis

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.concatenate([z,z],axis=1)#along second axis

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [ ]:
#for arrays with mixed dimensions-np.hstack,np.vstack
k=np.array([10,11,12])
np.vstack([z,k])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 11, 12]])

In [ ]:
l=np.array([[20],[21]])
np.hstack([z,l])

array([[ 1,  2,  3, 20],
       [ 4,  5,  6, 21]])

In [ ]:
#splitting of arrays
#np.split,np.hsplit,np.vsplit
x=[1,2,3,4,5,6,78,9,55,22]
x1,x2,x3=np.split(x,[3,5])
#create splits from -:3,3:5,5:
print(x1,x2,x3)

[1 2 3] [4 5] [ 6 78  9 55 22]


In [ ]:
grid=np.arange(16).reshape((4,4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
upper,lower=np.vsplit(grid,[2])
print(upper)
print(lower)


[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
left,right=np.hsplit(grid,[2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


**Computation on NumPy Arrays: Universal Functions**
Numpy provides an easy and flexible interface to optimized
computation with arrays of data.

The key to
making it fast is to use vectorized operations, generally implemented through NumPy’s universal functions (ufuncs).

**The Slowness of Loops**

In [ ]:
def reciprocal(values):
  output = np.empty(len(values))
  for i in range(len(values)):
    output[i]=1.0/values[i]
  return output



In [ ]:
big_array=np.random.randint(1,100,size = 1000000)
%timeit reciprocal(big_array)

1 loop, best of 3: 2.31 s per loop


bottleneck here is not the operations themselves, but the type-checking
and function dispatches that CPython must do at each cycle of the loop.
Each time
the reciprocal is computed, Python first examines the object’s type and does a
dynamic lookup of the correct function to use for that type.

**Introducing UFuncs**

In [ ]:
#vectorization-operation on the array
#This vectorized approach is designed to push the loop
# into the compiled layer that underlies NumPy, 
#leading to much faster execution
%timeit (1.0/big_array)

100 loops, best of 3: 2.84 ms per loop


Vectorized operations in NumPy are implemented via ufuncs.
Standard addition, subtraction, multiplication, and division
can all be used.

In [ ]:
x=np.array([1,2,3,4,5,6])
x+6
-x
2**x
-x
x%2

array([1, 0, 1, 0, 1, 0])

In [ ]:
np.add(x,2)

array([3, 4, 5, 6, 7, 8])

In [ ]:
#np.subtract,np.negative,np.multiply,np.divide,np.floor_divide,np.power,np.mod

In [ ]:
abs(x)

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.absolute(x)

array([1, 2, 3, 4, 5, 6])

In [ ]:
theta=np.linspace(0,np.pi,3)
theta

array([0.        , 1.57079633, 3.14159265])

In [ ]:
np.sin(theta)

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

In [ ]:
np.arcsin([-1,0,1])

array([-1.57079633,  0.        ,  1.57079633])

In [ ]:
np.exp2(x)

array([ 2.,  4.,  8., 16., 32., 64.])

In [ ]:
np.log10(x)

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ,
       0.77815125])

**Specialized ufuncs**

In [ ]:
from scipy import special

In [ ]:
x=[1,5,10]
special.gamma(x)

array([1.0000e+00, 2.4000e+01, 3.6288e+05])

In [ ]:
special.beta(x,2)

array([0.5       , 0.03333333, 0.00909091])

In [ ]:
#error function -integral of gaussian
x=np.array([0,0.3,0.7,1])
special.erf(x)

array([0.        , 0.32862676, 0.67780119, 0.84270079])

**Advanced Ufunc Features**

In [ ]:
#instead of creating temporary arrays,store the result in specified arrays
x=np.arange(5)

y=np.empty(5)
np.multiply(x,10,out=y)

array([ 0., 10., 20., 30., 40.])

In [ ]:
y=np.zeros(10)
np.power(2,x,out=y[::2])
print(y)

[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


**Aggregates**

In [ ]:
np.add.reduce(x)#gives sum
np.multiply.reduce(x)#gives product

0

In [ ]:
#to store all intermediate results of the computation
np.add.accumulate(x)

array([ 0,  1,  3,  6, 10])

In [ ]:
#outer products
np.multiply.outer(x,x)

array([[ 0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4],
       [ 0,  2,  4,  6,  8],
       [ 0,  3,  6,  9, 12],
       [ 0,  4,  8, 12, 16]])

**Aggregations: Min, Max, and Everything in Between**

In [ ]:
L=np.random.random(100)
%timeit sum(L)

100000 loops, best of 3: 18.3 µs per loop


In [ ]:
%timeit np.sum(L)

The slowest run took 16.80 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 3.94 µs per loop


Because it executes the operation in compiled code, NumPy’s version of the
operation is computed much more quickly

In [ ]:
%timeit min(big_array)
%timeit np.min(big_array)

10 loops, best of 3: 101 ms per loop
1000 loops, best of 3: 826 µs per loop


In [ ]:
big_array.min()

1

In [ ]:
#multidimensional aggregates
M=np.array(range(12)).reshape((3,4))
print(M)
#by default
M.sum()

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


66

In [ ]:
M.sum(axis=0)
#axis specifies the dimension of the array that will be collapsed

array([12, 15, 18, 21])

In [ ]:
M.sum(axis=1)

array([ 6, 22, 38])

most aggregates have a NaN-safe counterpart that computes
the result while ignoring missing values

In [ ]:
s=np.array([1,2,3,4,5,np.nan,33,np.nan])
np.nanmax(s)

33.0

In [ ]:
np.nanargmax(s)

6

**Computation on Arrays: Broadcasting**-another means of vectorization.
Broadcasting is simply a
set of rules for applying binary ufuncs (addition, subtraction, multiplication, etc.) on arrays of different sizes.

Broadcasting in NumPy follows a strict set of rules to determine the interaction
between the two arrays:
• Rule 1: If the two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is padded with ones on its leading (left) side.
• Rule 2: If the shape of the two arrays does not match in any dimension, the array
with shape equal to 1 in that dimension is stretched to match the other shape.
• Rule 3: If in any dimension the sizes disagree and neither is equal to 1, an error is
raised.

In [ ]:
import numpy as np
a=np.array([1,2,3])
print(a+5)
print(a.shape)

[6 7 8]
(3,)


We can think of this as an operation that stretches or duplicates the value 5 into the
array [5, 5, 5], and adds the results. The advantage of NumPy’s broadcasting is that
this duplication of values does not actually take place, but it is a useful mental model
as we think about broadcasting

In [ ]:
#broadcasting to arrays of higher dimensions
M=np.ones((3,3))
M+a

array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])

In [ ]:
#broadcasting of both arrays
a=np.arange(3)
b=np.arange(3)[:,np.newaxis]
print(a)
print(b)

[0 1 2]
[[0]
 [1]
 [2]]


In [ ]:
#stretched both a and b to match a common shape, and the result is a twodimensional
#array.
a+b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [ ]:
#Rule 1  and 2 example
M = np.ones((2, 3))
a = np.arange(3)
print(M.shape)
print(a.shape)


by rule 1-M.shape ->(2,3) and a.shape ->(1,3)

by rule 2-M.shape ->(2,3) and a.shape->(2,3)



In [ ]:
M+a

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [ ]:
#rule1,2,3
M=np.ones((3,2))
a=np.arange(3)


rule 1-M.shape ->(3,2) and a->(1,3)

rule 2-M.shape ->(3,2) and a ->(3,3)

rule 3-final shapes do not match,so error

In [ ]:
M+a

ValueError: ignored

In [ ]:
#logaddexp(a+b)=log(exp(a)+exp(b))

In [ ]:
#broadcasting example while dealing with data
#Imagine you have an array of 10 observations, each of which consists of 3 values.
X=np.random.random((10,3))
Xmean=X.mean(axis=0)
Xmean

array([0.52887708, 0.50464722, 0.52097069])

In [ ]:
X_centered=X-Xmean
X_centered

array([[ 0.30749428, -0.04276815,  0.32171347],
       [ 0.00681866,  0.43784589, -0.040432  ],
       [ 0.36703248, -0.42126033, -0.35943889],
       [-0.01342078, -0.34748197, -0.25659663],
       [-0.26186167, -0.30408804, -0.01876433],
       [ 0.34131167, -0.199811  ,  0.38495952],
       [-0.25384684,  0.4917393 ,  0.09271157],
       [-0.21795376,  0.25756832,  0.01215039],
       [-0.46954756,  0.45641722,  0.15934075],
       [ 0.19397353, -0.32816126, -0.29564385]])

**Comparison Operators as ufuncs**

The result of these comparison operators is always an array with a Boolean data type

In [ ]:
x=np.array([1,2,3,4,5])
x<3
#internally numpy uses np.less(x,3)

array([ True,  True, False, False, False])

**Working with Boolean Arrays**


In [ ]:
rng=np.random.RandomState(0)
x=rng.randint(10,size=(3,4))
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [ ]:
#counting enteries
#enteries less than 6
np.count_nonzero(x<6)

8

In [ ]:
#another way-here True is 1 and False is 0
np.sum(x<6)

8

In [ ]:
#along each row
np.sum(x<6,axis=1)

array([4, 2, 2])

In [ ]:
#to check whether any or all the values are true
#is any value greater than 8
np.any(x>8)

True

In [ ]:
#are all values equal to 6?
np.all(x==6)
#can be used along any particular axis as well

False

Warning-Python has built-in sum(), any(), and all() functions.
These have a different syntax than the NumPy versions, and in particular will fail or
produce unintended results when used on multidimensional arrays. Be sure that you
are using np.sum(), np.any(), and np.all() for these examples!

**Boolean operators**
Python’s bitwise logic operators, &, |, ^, and~.
NumPy overloads these as ufuncs that work element-wise on (usually
Boolean) arrays.


In [ ]:
np.sum((x>5)&(x<9))

3

In [ ]:
#use Boolean arrays as masks
x[x<5]

array([0, 3, 3, 3, 2, 4])

In [ ]:
#aggregate functions with boolean masking
np.max(x[x<5])

4

Remember-and and or perform a single Boolean evaluation on an entire
object, while & and | perform multiple Boolean evaluations on the content (the individual
bits or bytes) of an object.

**Fancy Indexing**
Fancy indexing is conceptually simple: it means passing an array of indices to access multiple array elements at once.

In [ ]:
x=np.random.randint(100,size=10)
x


array([45,  4, 53, 25, 48, 48, 66, 11, 87, 48])

In [ ]:
ind=[3,7,5]
x[ind]
#result reflects the shape of the index arrays
#rather than the shape of the array being indexed


array([25, 11, 48])

In [ ]:
#The pairing of indices in fancy indexing follows all the broadcasting rules
X = np.arange(12).reshape((3, 4))
row = np.array([0, 1, 2])
col = np.array([2, 1, 3])
X[row[:, np.newaxis], col]

array([[ 2,  1,  3],
       [ 6,  5,  7],
       [10,  9, 11]])

In [ ]:
#combine fancy indexing with slicing:
X[1:, [2, 0, 1]]

array([[ 6,  4,  5],
       [10,  8,  9]])

In [ ]:
row[:, np.newaxis].shape

(3, 1)

In [ ]:
#combine fancy indexing with masking
mask = np.array([1, 0, 1, 0], dtype=bool)
X[row[:, np.newaxis], mask]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

**Sorting Arrays**
By default np.sort uses an O[N log N] , quicksort
algorithm, though mergesort and heapsort are also available

In [ ]:
#sorted array without modifying the input
x=np.array([2,1,4,3,5])
np.sort(x)

array([1, 2, 3, 4, 5])

In [ ]:
#inplace sort
x.sort()
x

array([1, 2, 3, 4, 5])

In [ ]:
#argsort-returns indices of the sorted elements
x = np.array([2, 1, 4, 3, 5])
i = np.argsort(x)
print(i)


[1 0 3 2 4]


In [ ]:
#sorting rows or columns
rand = np.random.RandomState(42)
X = rand.randint(0, 10, (4, 6))
print(X)
np.sort(X,axis=0)#sort each column


[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]


array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [ ]:
#to find the K smallest values in the array
x = np.array([7, 2, 3, 1, 6, 5, 4])
np.partition(x, 3)

array([2, 1, 3, 4, 6, 5, 7])

**CHAPTER-3 PANDAS BASICS**

Pandas is a software library written for python that contains high level data structures and manipulation tools to make data analysis fast and easy in Python.

In [ ]:
#importing pandas

import pandas as pd



In [ ]:
#Series and Dataframes are two prominent data structures 
#that are imported from pandas library and are widely used
#in python




**PANDA SERIES**

Creating Series using List


In [ ]:

#Series having strings only 

#If the indexes are not given by us then the index is alloted 
#by pandas automatically starting from 0 to len(array) - 1 

animals = ['Tiger', ' Bear ' , ' Moose ' ]

pd.Series(animals)

0      Tiger
1      Bear 
2     Moose 
dtype: object

In [ ]:
#Note
#1. Underneath  Panda stores series values in a typed array using
#   the Numpy library.This allows significant speed- up when  
#    processing data versus traditional python lists.

#2. If we have strings and place None , pandas uses type object for 
#   underneath array. Same for strings and numbers; dtype will be 
#    shown as object. 

#3. If we have  int and float, pandas shows dtype as int64 and
#   float64 respectively.  

#4. If we have int or float with None , pandas shows dtype as float64 .
#   and denotes None as NaN which is a special floating point value 
#   that stands for means Not a Number.


**Dtype for different items in Series**

In [ ]:
#Series having Strings and integer(number)

animals = ['Tiger', ' Bear '  , '1' ]

pd.Series(animals)

0     Tiger
1     Bear 
2         1
dtype: object

In [ ]:
#Series having Strings and None

animals = ['Tiger', ' Bear ' , None  ]

pd.Series(animals)

0     Tiger
1     Bear 
2      None
dtype: object

In [ ]:
#Series having Strings , None and Integer

animals = ['Tiger', ' Bear ' , None , 1 ]

pd.Series(animals)

0     Tiger
1     Bear 
2      None
3         1
dtype: object

In [ ]:
#Series having float

numbers = [ 1.0 , 2.0 , 3.0 ]

pd.Series(numbers)

0    1.0
1    2.0
2    3.0
dtype: float64

In [ ]:
#Series having int

numbers = [ 1, 2 , 3 ]

pd.Series(numbers)

0    1
1    2
2    3
dtype: int64

In [ ]:
#Series having int and None

numbers = [ 1, 2 , 3 , None]

pd.Series(numbers)

0    1.0
1    2.0
2    3.0
3    NaN
dtype: float64

In [ ]:
# We can also create empty Series of a particular dtype

x = pd.Series( dtype = 'string' )


Creating Series from np array

In [ ]:
#Creating a Series from np array by specifying indexes

import numpy as np

data = np.array([ 'a' , 'b' , 'c', 'd' , 'e' ])

s1 = pd.Series( data , index = [ 'idx1 ' , 'idx2 ' , 'idx3 ' , 'idx4 ' , 'idx5 ' ] ) 

s1

idx1     a
idx2     b
idx3     c
idx4     d
idx5     e
dtype: object

**Creating Series from dictionary**

In [ ]:
import numpy as np

dict = { 'key1' : 1 , 'key2' : 2 , 'key3' : 3 , 'key4' : 4  }

s2 = pd.Series(dict)

s2

key1    1
key2    2
key3    3
key4    4
dtype: int64

**Creating Series from a Scalar**

In [ ]:
s3 = pd.Series( 6 , index = [1,2,3,4])

s3

1    6
2    6
3    6
4    6
dtype: int64

**Accessing Elements**

In [ ]:
data = np.array(['a', 'b' , 'c' , 'd' , 'e'])

s4 = pd.Series(data , index = [ 'idx1' , 'idx2' , 'idx3' , 'idx4' ,'idx5'] )

s4

idx1    a
idx2    b
idx3    c
idx4    d
idx5    e
dtype: object

In [ ]:
s4[0]

'a'

In [ ]:
#This will show the items from index 0 to 2 including 2

s4[:3]


idx1    a
idx2    b
idx3    c
dtype: object

In [ ]:

#Using indexes , we get the items from the starting index to the ending 
#index including the index

s4['idx1' : 'idx3']


idx1    a
idx2    b
idx3    c
dtype: object

In [ ]:
#To see index , use series_name.index
#s1.index() will give error as index is not callable.

s4.index

Index(['idx1', 'idx2', 'idx3', 'idx4', 'idx5'], dtype='object')

In [ ]:
s4.item

<bound method IndexOpsMixin.item of idx1    a
idx2    b
idx3    c
idx4    d
idx5    e
dtype: object>

In [ ]:
#head and tail

s4.head(2)

idx1    a
idx2    b
dtype: object

In [ ]:
s4.tail(3)

idx3    c
idx4    d
idx5    e
dtype: object

In [ ]:
#comparison with lists

l4 = ['a', 'b' , 'c ', 'd']

l4 = l4*2 

l4

['a', 'b', 'c ', 'd', 'a', 'b', 'c ', 'd']

In [ ]:
#with series

series= pd.Series(['a','b','c','d'])

series = series*2 

series

0    aa
1    bb
2    cc
3    dd
dtype: object

**PANDA DATAFRAME**

In [ ]:
#DataFrame is in table form while Series was in normal column form
#DataFrame has index for the column too while Series had index for 
#row only

In [ ]:

#Creating an empty dataframe

df = pd.DataFrame()

df

Empty DataFrame
Columns: []
Index: []

In [ ]:
#Creating DataFrame from list

l5 = [ 'a','b','c','d','e']

df = pd.DataFrame(l5)

df

0
0  a
1  b
2  c
3  d
4  e

In [ ]:
#Creating DataFrame from multiple list

l1 = [ ['abc' , 1 ] , [ 'bcd' , 2 ] , ['cde' , 3] ]

df = pd.DataFrame(l1)

df

0  1
0  abc  1
1  bcd  2
2  cde  3

In [ ]:
#Assigning Column Names

df = pd.DataFrame(l1, columns = ['Name', 'Age'])

df

Name  Age
0  abc    1
1  bcd    2
2  cde    3

In [ ]:
#Changing Data Type

df = pd.DataFrame(l1, columns = ['Name', 'Age'], dtype = float )

df

Name  Age
0  abc  1.0
1  bcd  2.0
2  cde  3.0

In [ ]:
#Creating dataframe from list of dictionaries
#In creating series, key of the dictionary used to become the index of series
#but in creating DataFrames, the key of dictionary becomes column of the 
#DataFrame

students = {'Name': ['Andrew', 'Michael', 'Ron', 'Stephen'], 'Age': [23, 22, 21,20], 'Marks': [98, 67, 78, 89]}

df = pd.DataFrame(students)

df

Name  Age  Marks
0   Andrew   23     98
1  Michael   22     67
2      Ron   21     78
3  Stephen   20     89

In [ ]:
#Changing the indexes

df = pd.DataFrame(students, index = ['grade1', 'grade2', 'grade3', 'grade4'])

df


Name  Age  Marks
grade1   Andrew   23     98
grade2  Michael   22     67
grade3      Ron   21     78
grade4  Stephen   20     89

In [ ]:
#Rows selection - Using loc , iloc

df = pd.DataFrame(students, index = ['grade1', 'grade2', 'grade3', 'grade4'])

df

df.loc['grade1': 'grade3']


Name  Age  Marks
grade1   Andrew   23     98
grade2  Michael   22     67
grade3      Ron   21     78

In [ ]:
df.iloc[0:3]

Name  Age  Marks
grade1   Andrew   23     98
grade2  Michael   22     67
grade3      Ron   21     78

In [ ]:

#Column Selection - Using iLoc

df.iloc[ : , 0:2 ]


Name  Age
grade1   Andrew   23
grade2  Michael   22
grade3      Ron   21
grade4  Stephen   20

In [ ]:
#Deleting multiple rows

df.drop(['grade2', 'grade3'], inplace = True)

df


Name  Age  Marks
grade1   Andrew   23     98
grade4  Stephen   20     89

In [ ]:
#Adding new columns and Addition

df['Bonus']=pd.DataFrame([10,20,30,40],index=['grade1','grade2','grade3','grade4'])

df['Sum'] = df['Age'] + df['Marks'] + df['Bonus']

df


Name  Age  Marks  Bonus  Sum
grade1   Andrew   23     98     10  131
grade4  Stephen   20     89     40  149

In [ ]:

#Addition using iLoc, column wise

df['Sum'] = df.iloc[:, 0:3].sum(axis = 1)

df



Name  Age  Marks  Bonus  Sum
grade1   Andrew   23     98     10  121
grade4  Stephen   20     89     40  109

In [ ]:
#Copy DataFrame

df1 = df.copy()

df1


Name  Age  Marks  Bonus  Sum
grade1   Andrew   23     98     10  121
grade4  Stephen   20     89     40  109

In [ ]:
#Deleting columns

del(df1['Name'])

df1

Age  Marks  Bonus  Sum
grade1   23     98     10  121
grade4   20     89     40  109

In [ ]:
df1.pop('Age')

df1


Marks  Bonus  Sum
grade1     98     10  121
grade4     89     40  109

In [ ]:

df


Name  Age  Marks  Bonus  Sum
grade1   Andrew   23     98     10  121
grade4  Stephen   20     89     40  109

In [ ]:
#Reordering of Columns

df = df[['Marks', 'Bonus', 'Sum', 'Age', 'Name']]

df


Marks  Bonus  Sum  Age     Name
grade1     98     10  121   23   Andrew
grade4     89     40  109   20  Stephen

In [ ]:
#Filtering Data
df.loc[df['Name'] == 'Stephen']

Marks  Bonus  Sum  Age     Name
grade4     89     40  109   20  Stephen

In [ ]:
df.loc[(df['Sum'] > 85) & (df['Sum'] < 115)]


Marks  Bonus  Sum  Age     Name
grade4     89     40  109   20  Stephen

In [ ]:
#Methods

dict1 = {'Name': pd.Series(['Martin', 'Jack', 'Mary', 'David', 'Stephen', 'Shannon', 'Angela', 'Stephanie', 'Philip', 'Michael']), 
        'Age': pd.Series([34,23,56,34,27,43,33,54,44,41]), 'Rating': pd.Series([4.23,3.24,3.98,2.56,3.20,4.6,3.8,3.78,2.98,4.80])}

dfg = pd.DataFrame(dict1)

dfg

Name  Age  Rating
0     Martin   34    4.23
1       Jack   23    3.24
2       Mary   56    3.98
3      David   34    2.56
4    Stephen   27    3.20
5    Shannon   43    4.60
6     Angela   33    3.80
7  Stephanie   54    3.78
8     Philip   44    2.98
9    Michael   41    4.80

In [ ]:
#Transpose

dfg.T


0     1     2      3  ...       6          7       8        9
Name    Martin  Jack  Mary  David  ...  Angela  Stephanie  Philip  Michael
Age         34    23    56     34  ...      33         54      44       41
Rating    4.23  3.24  3.98   2.56  ...     3.8       3.78    2.98      4.8

[3 rows x 10 columns]

In [ ]:
#axes
#For columns too, it is called index in DataFrame

dfg.axes


[RangeIndex(start=0, stop=10, step=1),
 Index(['Name', 'Age', 'Rating'], dtype='object')]

In [ ]:
#datatypes

dfg.dtypes


Name       object
Age         int64
Rating    float64
dtype: object

In [ ]:
#shapes

dfg.shape


(10, 3)

In [ ]:
#Size

dfg.size

30

In [ ]:
#Values

dfg.values


array([['Martin', 34, 4.23],
       ['Jack', 23, 3.24],
       ['Mary', 56, 3.98],
       ['David', 34, 2.56],
       ['Stephen', 27, 3.2],
       ['Shannon', 43, 4.6],
       ['Angela', 33, 3.8],
       ['Stephanie', 54, 3.78],
       ['Philip', 44, 2.98],
       ['Michael', 41, 4.8]], dtype=object)

In [ ]:

#sum, mean, std, count

dfg.sum()


Name      MartinJackMaryDavidStephenShannonAngelaStephan...
Age                                                     389
Rating                                                37.17
dtype: object

In [ ]:

dfg.sum(axis = 1) 


0    38.23
1    26.24
2    59.98
3    36.56
4    30.20
5    47.60
6    36.80
7    57.78
8    46.98
9    45.80
dtype: float64

In [ ]:

dfg.mean()


Age       38.900
Rating     3.717
dtype: float64

In [ ]:

dfg.std()


Age       10.774971
Rating     0.720525
dtype: float64

In [ ]:
dfg.count(axis = 1) 


0    3
1    3
2    3
3    3
4    3
5    3
6    3
7    3
8    3
9    3
dtype: int64

In [ ]:

#Data Summary - shows summary of statistics

dfg.describe()


Age     Rating
count  10.000000  10.000000
mean   38.900000   3.717000
std    10.774971   0.720525
min    23.000000   2.560000
25%    33.250000   3.210000
50%    37.500000   3.790000
75%    43.750000   4.167500
max    56.000000   4.800000

In [ ]:
#Sorting
#By Index
#By default, in this function, ascending is always True

sorted_dfg = dfg.sort_index(ascending = False)

sorted_dfg


Name  Age  Rating
9    Michael   41    4.80
8     Philip   44    2.98
7  Stephanie   54    3.78
6     Angela   33    3.80
5    Shannon   43    4.60
4    Stephen   27    3.20
3      David   34    2.56
2       Mary   56    3.98
1       Jack   23    3.24
0     Martin   34    4.23

In [ ]:
#Sorting by Values

sorted_age= dfg.sort_values('Age')

sorted_age


Name  Age  Rating
1       Jack   23    3.24
4    Stephen   27    3.20
6     Angela   33    3.80
0     Martin   34    4.23
3      David   34    2.56
9    Michael   41    4.80
5    Shannon   43    4.60
8     Philip   44    2.98
7  Stephanie   54    3.78
2       Mary   56    3.98

In [ ]:
#Dataframe with missing values

raw_data = {'first_name': ['Martin', 'Jack', np.nan, 'David', 'Stephen'], 
            'last_name': ['Duston', np.nan, 'Miller', 'Ross', 'Still'],
            'age': [42, 36, np.nan, 24, 73], 
            'sex': ['m', np.nan, np.nan, 'f', np.nan],
            'preTestScore': [4, np.nan, 2, np.nan,  3],
            'postTestScore': [25, np.nan, np.nan, 62, 70]}

df = pd.DataFrame(raw_data, columns = ['first_name', 'last_name', 'age', 'sex', 'preTestScore', 'postTestScore'])




In [ ]:
#identifying the missing values

df.isnull()


first_name  last_name    age    sex  preTestScore  postTestScore
0       False      False  False  False         False          False
1       False       True  False   True          True           True
2        True      False   True   True         False           True
3       False      False  False  False          True          False
4       False      False  False   True         False          False

In [ ]:

df.isnull().sum()


first_name       1
last_name        1
age              1
sex              3
preTestScore     2
postTestScore    2
dtype: int64

In [ ]:

#Drop rows with missing values

df_drop = df.dropna()

df_drop



first_name last_name   age sex  preTestScore  postTestScore
0     Martin    Duston  42.0   m           4.0           25.0

In [ ]:
#Create a new column full of missing values

df['new'] = np.nan

df

first_name last_name   age  sex  preTestScore  postTestScore  new
0     Martin    Duston  42.0    m           4.0           25.0  NaN
1       Jack       NaN  36.0  NaN           NaN            NaN  NaN
2        NaN    Miller   NaN  NaN           2.0            NaN  NaN
3      David      Ross  24.0    f           NaN           62.0  NaN
4    Stephen     Still  73.0  NaN           3.0           70.0  NaN

In [ ]:
#Drop column if they only contain missing values

df.dropna(axis=1,how="all",inplace=True)

df

first_name last_name   age  sex  preTestScore  postTestScore
0     Martin    Duston  42.0    m           4.0           25.0
1       Jack       NaN  36.0  NaN           NaN            NaN
2        NaN    Miller   NaN  NaN           2.0            NaN
3      David      Ross  24.0    f           NaN           62.0
4    Stephen     Still  73.0  NaN           3.0           70.0

In [ ]:

#Fill in missing data with Zeros

df.fillna(0)


first_name last_name   age sex  preTestScore  postTestScore
0     Martin    Duston  42.0   m           4.0           25.0
1       Jack         0  36.0   0           0.0            0.0
2          0    Miller   0.0   0           2.0            0.0
3      David      Ross  24.0   f           0.0           62.0
4    Stephen     Still  73.0   0           3.0           70.0

In [ ]:
#Fill in missing in specific col with the mean value of that col

df["preTestScore"].fillna(df["preTestScore"].mean(),inplace=True)

df


first_name last_name   age  sex  preTestScore  postTestScore
0     Martin    Duston  42.0    m           4.0           25.0
1       Jack       NaN  36.0  NaN           3.0            NaN
2        NaN    Miller   NaN  NaN           2.0            NaN
3      David      Ross  24.0    f           3.0           62.0
4    Stephen     Still  73.0  NaN           3.0           70.0

In [ ]:
# Select the rows of df where age is not NaN and last_name is not NaN

df[df['age'].notnull() & df['last_name'].notnull()]


first_name last_name   age  sex  preTestScore  postTestScore
0     Martin    Duston  42.0    m           4.0           25.0
3      David      Ross  24.0    f           3.0           62.0
4    Stephen     Still  73.0  NaN           3.0           70.0

**Chapter 4- SciPy**

SciPy is a collection of mathematical algorithms and convenience functions built on the NumPy extension of Python.It adds significant power to the interactive Python session by providing the user with high-level commands and classes for manipulating and visualizing data. 

**SciPy Constants**

As SciPy is more focused on scientific implementations, it provides many built-in scientific constants.
These constants can be helpful when you are working with Data Science.

In [ ]:
import scipy

In [ ]:
from scipy import constants

print(constants.pi)

3.141592653589793


In [ ]:
print(dir(constants))

['Avogadro', 'Boltzmann', 'Btu', 'Btu_IT', 'Btu_th', 'ConstantWarning', 'G', 'Julian_year', 'N_A', 'Planck', 'R', 'Rydberg', 'Stefan_Boltzmann', 'Wien', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_obsolete_constants', 'absolute_import', 'acre', 'alpha', 'angstrom', 'arcmin', 'arcminute', 'arcsec', 'arcsecond', 'astronomical_unit', 'atm', 'atmosphere', 'atomic_mass', 'atto', 'au', 'bar', 'barrel', 'bbl', 'blob', 'c', 'calorie', 'calorie_IT', 'calorie_th', 'carat', 'centi', 'codata', 'constants', 'convert_temperature', 'day', 'deci', 'degree', 'degree_Fahrenheit', 'deka', 'division', 'dyn', 'dyne', 'e', 'eV', 'electron_mass', 'electron_volt', 'elementary_charge', 'epsilon_0', 'erg', 'exa', 'exbi', 'femto', 'fermi', 'find', 'fine_structure', 'fluid_ounce', 'fluid_ounce_US', 'fluid_ounce_imp', 'foot', 'g', 'gallon', 'gallon_US', 'gallon_imp', 'gas_constant', 'gibi', 'giga', 'golden', 'golden_ratio', 'gra

Unit Categories
The units are placed under these categories:

Metric

Binary

Mass

Angle

Time

Length

Pressure

Volume

Speed

Temperature

Energy

Power

Force

In [ ]:
print(constants.gram)

In [ ]:
print(constants.degree)

In [ ]:
print(constants.minute) 

**SciPy Optimization and root finding**

SciPy optimize provides functions for minimizing (or maximizing) objective functions, possibly subject to constraints. It includes solvers for nonlinear problems (with support for both local and global optimization algorithms), linear programing, constrained and nonlinear least-squares, root finding, and curve fitting.



In [ ]:
#finding the root
from scipy.optimize import root

def eqn(x):
  return x**2-4*x+4

myroot = root(eqn, 0)

print(myroot.x)

[1.99999999]


In [ ]:
print(myroot)

    fjac: array([[-1.]])
     fun: array([0.])
 message: 'The solution converged.'
    nfev: 41
     qtf: array([-4.4408921e-16])
       r: array([4.41088521e-08])
  status: 1
 success: True
       x: array([1.99999999])


In [ ]:
from scipy.optimize import minimize

def eqn(x):
  return x**2 + x + 2

mymin = minimize(eqn, 0, method='BFGS')

print(mymin)

      fun: 1.75
 hess_inv: array([[0.50000001]])
      jac: array([0.])
  message: 'Optimization terminated successfully.'
     nfev: 12
      nit: 2
     njev: 4
   status: 0
  success: True
        x: array([-0.50000001])


**SciPy Sparse Data**

Sparse Data: is a data set where most of the item values are zero.

Dense Array: is the opposite of a sparse array: most of the values are not zero.



SciPy has a module, scipy.sparse that provides functions to deal with sparse data.

There are primarily two types of sparse matrices that we use:

CSC - Compressed Sparse Column. For efficient arithmetic, fast column slicing.

CSR - Compressed Sparse Row. For fast row slicing, faster matrix vector products

In [ ]:
import numpy as np
from scipy.sparse import csr_matrix

arr = np.array([0, 0, 0, 0, 0, 1, 1, 0, 2])

print(csr_matrix(arr))

  (0, 5)	1
  (0, 6)	1
  (0, 8)	2
